server:
  port: 8222

spring:
  application:
    name: yue0shop-gateway
  cloud:
    gateway:
      routes:
        - id: yue0shop-user
          uri: lb://yue0shop-user
          predicates:
            - Path=/yue0shop-user/**
          filters:
            - StripPrefix=1

        - id: yue0shop-web
          uri: lb://yue0shop-web
          predicates:
            - Path=/yue0shop-web/**
          filters:
            - StripPrefix=1
springdoc:
  swagger-ui:
    urls:
      - name: yue0shop-user
        url: /yue0shop-user/v3/api-docs
      - name: yue0shop-web
        url: /yue0shop-web/v3/api-docs

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka
  instance:
    prefer-ip-address: true